Upload Rust results

diff --git a/.github/workflows/_arbitrator.yml b/.github/workflows/_arbitrator.yml
--- a/.github/workflows/_arbitrator.yml
+++ b/.github/workflows/_arbitrator.yml
@@ -56,7 +56,25 @@ jobs:
 #        run: cargo clippy --all --manifest-path arbitrator/Cargo.toml -- -D warnings
 
       - name: Run rust tests
-        run: cargo nextest run -p arbutil -p prover -p jit -p stylus --release --manifest-path arbitrator/prover/Cargo.toml --profile ci --config-file nextest.toml
+        id: run-rust-tests
+        continue-on-error: true
+        run: |
+          cargo nextest run -p arbutil -p prover -p jit -p stylus --release \
+            --manifest-path arbitrator/prover/Cargo.toml \
+            --profile ci --config-file nextest.toml
+
+      - name: Upload rust test results
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: rust-junit-reports
+          path: ./arbitrator/target/nextest/ci/junit.xml
+
+      - name: Fail if rust tests failed
+        if: steps.run-rust-tests.outcome == 'failure'
+        run: |
+          echo "Rust tests failed. Failing the workflow as required."
+          exit 1
 
 #      - name: Check stylus_bechmark
 #        run: cargo check --manifest-path arbitrator/tools/stylus_benchmark/Cargo.toml
